import 'dart:async';
import 'dart:core';
import 'dart:io';
import 'dart:convert';
import 'dart:typed_data';
import 'dart:math';
import 'package:pointycastle/api.dart' as crypto hide PublicKey ;
import 'package:pointycastle/export.dart' hide PublicKey;
import 'package:pointycastle/key_derivators/ecdh_kdf.dart';
import 'package:pointycastle/pointycastle.dart' hide PublicKey;
import 'package:dartsv/dartsv.dart';
import 'package:encrypt/encrypt.dart' hide SecureRandom;
import 'package:path_provider/path_provider.dart';
import 'package:flutter/foundation.dart' hide Key  ;
import 'package:flutter/foundation.dart' show kDebugMode  ;
import 'package:basic_utils/basic_utils.dart' as x509 hide ASN1ObjectType;
import 'package:basic_utils/basic_utils.dart' as crypto_utils hide ASN1ObjectType, SecureRandom ;
import 'package:device_info_plus/device_info_plus.dart';
import 'package:basic_utils/basic_utils.dart' hide SecureRandom ;
import 'package:android_id/android_id.dart';
import 'package:nodeid/nodeid.dart';
import 'package:pointycastle/asymmetric/api.dart'  ; // Potentially needed
import 'package:cryptography/cryptography.dart' ;





String mserverurl = "http://ictwiki.iitk.ac.in:8080/b4server";   // server url of b4 auth server


/// CertificateData
///
/// class had been used so that when the self signed certificate has been generated by the user
/// it's other parameters like public and private keys can also be accessed in a structured manner in other functions
class CertificateData {
    String privateKeyPem;
    //String publicKeyPem;
    String x509cert;
    //String csr;  // the csr is used because it will again be used to generate a cert and sign it by server private key
    CertificateData({
        required this.privateKeyPem,
        //required this.publicKeyPem,
        required this.x509cert,
        //required this.csr,
    });
}

/// generatedCertificate
///
/// has been used so that the certificate , public and private keys generated once can be
/// later on called in different functions as and when required.
CertificateData? generatedCertificate;



/// AuthManager
///
/// class has been made which is a library of various functions used in certificate creation,
/// authentication from server and later on self authentication at user end every time the user opens the application.
class AuthManager {
    String privateKeyPem = "";
    String publicKeyPem = "";
    String x509cert = "";
    String country = "";
    String organization = "";
    String commonName = "";
    String surname = "";
    String stateOrProvinceName = "";
    String givenName ="";
    String userID = "";

/// generateSelfSignedUserCertificate
    ///
    /// This function is used to take attributes from the user like country, organization,
    ///commonName, surname,  stateOrProvinceName,  givenName for user AADHAR ID, userID for user Email ID
    ///and then generate a X509 self signed certificate as Certificate Data in which we have
    ///the certificate, private key and public key which will be saved in secure storage(temporarily) and later on
    ///it will be sent to auth server for signature and the signed certificate returned from server will overwrite
    ///the self signed certificate only in secure storage but keys will not be changed.
    Future<CertificateData?> generateSelfSignedUserCertificate(String country, String organization,
            String commonName,String surname, String stateOrProvinceName, String givenName,String userID) async {

        final attributes = {
'C': country,
'O': organization,
'CN': commonName,
'SN': surname,
'ST': stateOrProvinceName,
'GN': givenName,  // for user Aadhar ID
'UID': userID,    // for user email ID
        };
        final eccKeyPair = crypto_utils.CryptoUtils.generateEcKeyPair();
        final privateKey = eccKeyPair.privateKey as x509.ECPrivateKey;
        //File('C:\\Users\\HP\\Desktop\\b4testdata\\privateKeyOnly').writeAsBytesSync(privateKey as List<int>);
        final publicKey = eccKeyPair.publicKey as x509.ECPublicKey;
        final privateKeyPem = crypto_utils.CryptoUtils.encodeEcPrivateKeyToPem(privateKey);
        //final publicKeyPem = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(publicKey);
        final csr = x509.X509Utils.generateEccCsrPem(attributes, privateKey, publicKey);
        final x509cert = x509.X509Utils.generateSelfSignedCertificate(privateKey, csr, 365);

        if (kDebugMode) {
            //print('\nPrivate Key Pem :\n$privateKeyPem');
            //print('\nPublic Key Pem :\n$publicKeyPem');
            //print('\nUser Certificate:\n$x509cert');


        }


        generatedCertificate = CertificateData(
                                   privateKeyPem: privateKeyPem,
                                   //publicKeyPem: publicKeyPem,
                                   x509cert: x509cert,
                                   //csr: csr
        );


        return generatedCertificate;
    }



    /// verifyServerSignature
    ///
    /// The purpose of this function is to check the server signature for authenticity. It compares the
    /// server certificate which is part of the application code and the signed certificate of the user
    /// returned from the server which was saved in the secure storage the certificateServerSignatureVerification
    /// is a bool which will be true only if the server public key in both certificates is same.
    /// If this fails then it means the certificate has been tampered and the user now has to generate a new certificate.
    Future<bool> verifyServerSignature(serverSignedCertificate, serverCertificate) async {
        try {
            //final data1Future = readFromLocalStorage(LocalStorageValueType.serverCertificate);
            //final serverCertificate = await data1Future;
            final certificateServerSignatureVerification = x509.X509Utils.checkX509Signature
            (serverSignedCertificate, parent: serverCertificate);
            if (certificateServerSignatureVerification) {
                if (kDebugMode) {
                    print('Certificate signature is valid.');
                }
            } else {
                if (kDebugMode) {
                    print('Certificate signature is NOT valid.');
                }
            }
            return certificateServerSignatureVerification;
        } catch (e) {
            if (kDebugMode) {
                //print('Error during certificate signature verification: $e');
            }
            return false;
        }
    }



    /// Create Digital Signature
    ///
    /// This function is used to take data input from the user and  create a digital signature by using
    /// user's private key and return the digital signature in String format.
    Future<String> createDigitalSignature(String content, privateKeyPemDecrypted) async
    {
        Uint8List dataToSign = Uint8List.fromList(utf8.encode(content));
        final privateKey = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(privateKeyPemDecrypted);
        final digSign = crypto_utils.CryptoUtils.ecSign(privateKey, dataToSign);
        final digitalSignature = crypto_utils.CryptoUtils.ecSignatureToBase64(digSign);
        return digitalSignature;
    }



/// createMessageForAuthentication
    ///
    /// This function is used to create a message with the help of create digital signature , the content along with the signate will be sent for
    /// authentication.
    Future<String> createMessageForAuthentication(String content, privateKeyPemDecrypted) async
    {
      final signature = await createDigitalSignature(content, privateKeyPemDecrypted);
      Map<String, dynamic> messageJson = {
        "signature": signature,
        "content": content,
      };
      final message = jsonEncode(messageJson);
      return message;
    }


/// checkMessageForAuthentication
    ///
    /// This function will be used to check the integrity of the content in the message if the content is not tampered then it will return the string
    /// else it will give null.
    Future<String?> checkMessageForAuthentication(String message, userCert) async {
      try {
        // Parse the JSON message to extract the signature and content
        Map<String, dynamic> messageJson = jsonDecode(message);
        String signature = messageJson["signature"];
        String content = messageJson["content"];
        Uint8List contentBytes = utf8.encode(content);
        final publicKeyPem = await extractPublicKeyFromCertificate(userCert);
        final publicKey = crypto_utils.CryptoUtils.ecPublicKeyFromPem(publicKeyPem);
        bool isSignatureValid = crypto_utils.CryptoUtils.ecVerifyBase64(publicKey ,contentBytes,signature);
        // If the signature is valid, return the content; otherwise, return null
        if (isSignatureValid) {
          return content;
        } else {
          return null;
        }
      } catch (e) {
        // Handle JSON parsing errors or signature verification errors
        print("Error checking message: $e");
        return null;
      }
    }




    /// validateTime
    ///
    /// The purpose of this function is to access the signed certificate from secure storage and check it's validity
    /// weather the certificate has expired or not. Validity is for 365 days, after that the user needs to again
    /// generate a new certificate and get it signed from server. It returns a isValid bool value which is true only if
    /// the certificate has not expired. If the validity has expired the application
    /// will not start functioning  properly till the time the certificate has been renewed.
    ///
    Future<bool> validateTime(String decryptedServerSignedCertificate) async {
        try {
            final validityDuration = x509.X509Utils.x509CertificateFromPem(decryptedServerSignedCertificate);
            final creationDateTime = validityDuration.tbsCertificate?.validity.notBefore;
            final expiryDateTime = validityDuration.tbsCertificate?.validity.notAfter;

            if (creationDateTime != null && expiryDateTime != null) {
                // Print creation and expiry date times
                print('Certificate Creation Date and Time: $creationDateTime');
                print('Certificate Expiry Date and Time: $expiryDateTime');

                // Check if the current date and time are within the validity period
                final currentDate = DateTime.now();
                final isValid = currentDate.isAfter(creationDateTime) && currentDate.isBefore(expiryDateTime);

                // Print whether the certificate is valid or not
                //print('Is Certificate Valid: $isValid');

                if (isValid) {
                    // Calculate and print the remaining validity duration in days
                    final remainingDays = max(0, expiryDateTime.difference(currentDate).inDays);
                    print('Remaining Validity Duration: $remainingDays days');
                }

                return isValid;
            }

            if (kDebugMode) {
                print('Error during validity check: Invalid decryptedValues.');
            }
            return false;
        } catch (e) {

            if (kDebugMode) {
                print('Error during validity check: $e');
            }
            return false;
        }
    }


    /// verifyEmailInServerDatabase
    ///
    /// Verifies the email in the server database.This function sends a request to the server to check if the given email
    /// exists in the server's database. It constructs the request URL using the
    /// provided [email], sends the request, and waits for the response. The
    /// response is then checked to determine if the email exists or not.
    ///
    /// If the response is '14', the email exists on the server, and then the user can download its previous certificate
    /// from the auth server . If the response is '15', the email does not exist on the server, and it is a new user
    /// and they need to create a new certificate .Any other response indicates an error in the email verification process.
    ///
    /// Returns the response received from the server 14 0r 15 as a String.
    Future<String> verifyEmailInServerDatabase(String email) async{
        String MSrequrl = "$mserverurl/ProcessRequest?req=checkkeystore&emailid=$email";
        String emailVerificationResponse=await x509.HttpUtils.postForString(MSrequrl);
        emailVerificationResponse=emailVerificationResponse.trim();
        //print('Response from server is : $emailVerificationResponse');
        if ((emailVerificationResponse.compareTo("14"))==0) {
            // print('Your email id exist on server do you want to download your certificate');
        }
        else if ((emailVerificationResponse.compareTo("15"))==0) {
            // print('Your email id DOES NOT exist on server do you want to create new certificate');
        }
        else {
            print('error in email verification');
        }
        return emailVerificationResponse;
    }


    ///sendSelfSignedCertificateToServer
    ///
    /// This function is used to send the self signed certificate generated by the user
    /// to the server for further authentication procedure. As a response to this the server will send an OTP to
    /// email id mentioned in the attributes userID of the user certificate.
    Future<void> sendSelfSignedCertificateToServer(selfSignedCertificate) async{
        //String selfSignedCertificate = generatedCertificate!.x509cert;
        //final selfSignedCertificateFuture = readFromLocalStorage(LocalStorageValueType.serverCertificate);
        //final selfSignedCertificate = await selfSignedCertificateFuture;
        var certstr = Uri.encodeComponent(selfSignedCertificate);
        String mserverurl = "http://ictwiki.iitk.ac.in:8080/b4server";
        String MSrequrl = "$mserverurl/ProcessRequest?req=sscccertsign&cert=${certstr}";
        String responseAfterSendingCertificate = await x509.HttpUtils.postForString(MSrequrl);
        responseAfterSendingCertificate=responseAfterSendingCertificate.trim();
        //print("Response of server after receiving self signed certificate is: $responseAfterSendingCertificate");
        //return responseAfterSendingCertificate;
    }


    /// getDeviceId
    ///
    /// This function is used to retrieve the MAC ADDRESS of the device which will be sent to auth server
    /// during authentication process.
    Future<String?> getDeviceId() async {
        final DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
        String? deviceId;
        try {
            if (Platform.isAndroid) {
                const androidId = AndroidId();
                deviceId = await androidId.getId();// Android device ID
            } else if (Platform.isIOS) {
                IosDeviceInfo iosInfo = await deviceInfo.iosInfo;
                deviceId = iosInfo.identifierForVendor; // iOS device ID
            } else if(kIsWeb) {
                final webBrowserInfo = await deviceInfo.webBrowserInfo;
                deviceId = '${webBrowserInfo.vendor ?? '-'} + ${webBrowserInfo.userAgent ?? '-'} + ${webBrowserInfo.hardwareConcurrency.toString()}';// browser device id
            } else if(Platform.isWindows) {
                final windowsInfo = await deviceInfo.windowsInfo;
                deviceId = windowsInfo.deviceId; // windows device id
            } else if(Platform.isLinux) {
                final linuxInfo = await deviceInfo.linuxInfo;
                deviceId = linuxInfo.machineId;// Linux device id
            } else if (Platform.isMacOS) {
                final macOsInfo = await deviceInfo.macOsInfo;
                deviceId = macOsInfo.systemGUID;// Mac device id
            }
            /*    setState(() {
                      did = deviceId;
                  });
                  */
        } catch (e) {
            deviceId = "Error getting device ID: $e";
        }
        int? len=deviceId?.length;
        deviceId=deviceId?.substring(1,len!-1);
        print('Device ID: $deviceId');

        return deviceId;
    }


/// sendOTPAndDataToServer
    ///
    /// This function will send the OTP, device id, node id and self signed certificate to the auth server
    /// and in response it will finally receive the server certificate and server signed certificate,
    /// which will then be stored in trust store of the user.
    Future<Map<String, String>> sendOtpNodeIdDeviceIdSelfSignedCertificateToServer(String otp, selfSignedCertificate, nodeId) async {
        //var nodeIdFuture = readFromLocalStorage(LocalStorageValueType.nodeid);
       // String? nodeId = await nodeIdFuture;
      // In test code the node id has been passed , but actually this node id will be read by auth storage and then
      // passed to this function.
        print(" the value of stored node id called to sent is: $nodeId");


/// this device id has been hard coded for testing purpose only
        /// because during testing we don't have access to physical hardware
        /// but the  function mentioned below works when we build the app on flutter.
        const deviceId = 'D6C62E4E-4FB3-4D42-9182-34A99D20FB91';
        //final  deviceId = await getDeviceId();
        // print(" the value of device is $deviceId");

        var selfSignedCertificateStr = Uri.encodeComponent(selfSignedCertificate);
Map<String, dynamic> myData = { 'selfSignedCertificateStringByte': selfSignedCertificateStr };
        String jsonBody = json.encode(myData);
        String MSrequrl = "$mserverurl/otp_verification?req=otpverify&OTP=$otp&cert=$selfSignedCertificateStr&jsonbody=$jsonBody&deviceid=${deviceId}&nodeid=$nodeId";
        String serverSignedCertificateBase64Received = await x509.HttpUtils.postForString(MSrequrl);
        String serverSignedCertificateBase64 = serverSignedCertificateBase64Received.trim();
        String delimiter = "ClientCert";
        List<String> parts = serverSignedCertificateBase64.split(delimiter);
        String serverCertificateString = parts[0];
        String signedClientCertificateString = parts[1];
        Uint8List decodedBytesServerSignedCertificateBase64 = base64.decode(signedClientCertificateString);
        ASN1Parser asn1Parser = ASN1Parser(decodedBytesServerSignedCertificateBase64);
        ASN1Sequence sequence = asn1Parser.nextObject() as ASN1Sequence;
        ASN1Object object = ASN1Object.fromBytes(sequence.encodedBytes);
        final serverSignedCertificatePem = x509.X509Utils.encodeASN1ObjectToPem(object,'-----BEGIN CERTIFICATE-----', '-----END CERTIFICATE-----');
        print('server signed cert received : $serverSignedCertificatePem');
        final serverSignedCertificateFromAuthServer = x509.X509Utils.x509CertificateFromPem(serverSignedCertificatePem) ;
        print('SUBJECT: ${serverSignedCertificateFromAuthServer.tbsCertificate?.subject}');
        print('ISSUER: ${serverSignedCertificateFromAuthServer.tbsCertificate?.issuer}');
        //print('VERSION: ${serverSignedCertificateFromAuthServer.tbsCertificate?.version}');
        //print('SERIAL NUMBER: ${serverSignedCertificateFromAuthServer.tbsCertificate?.serialNumber}');
        //print('VALID FROM: ${serverSignedCertificateFromAuthServer.tbsCertificate?.validity.notBefore}');
        print('VALID UNTIL: ${serverSignedCertificateFromAuthServer.tbsCertificate?.validity.notAfter}');
        //print('SIGNATURE ALGORITHM: ${serverSignedCertificateFromAuthServer.tbsCertificate?.signatureAlgorithm}');
        print('PUBLIC KEY ALGORITHM: ${serverSignedCertificateFromAuthServer.tbsCertificate?.subjectPublicKeyInfo.algorithmReadableName}');
        //print('PUBLIC KEY SHA 256 VALUE: ${serverSignedCertificateFromAuthServer.tbsCertificate?.subjectPublicKeyInfo.sha256Thumbprint}');

        //print('server signed cert received in x509 format is: $serverSignedCertificateFromAuthServer');
        File('C:\\Users\\HP\\Desktop\\b4testdata\\serverSignedCertificateFromAuthServer.pem').writeAsStringSync(serverSignedCertificatePem);


        Uint8List decodedBytesServerCertificateBase64 = base64.decode(serverCertificateString);
        ASN1Parser asn1ParserServer = ASN1Parser(decodedBytesServerCertificateBase64);
        ASN1Sequence sequenceServer = asn1ParserServer.nextObject() as ASN1Sequence;
        ASN1Object objectServer = ASN1Object.fromBytes(sequenceServer.encodedBytes);
        final serverCertificatePem = x509.X509Utils.encodeASN1ObjectToPem(objectServer,'-----BEGIN CERTIFICATE-----', '-----END CERTIFICATE-----');
        print('server cert received : $serverCertificatePem');
        final serverCertificateFromAuthServer = x509.X509Utils.x509CertificateFromPem(serverCertificatePem) ;
        print('SUBJECT: ${serverCertificateFromAuthServer.tbsCertificate?.subject}');
        print('ISSUER: ${serverCertificateFromAuthServer.tbsCertificate?.issuer}');
        //print('VERSION: ${serverCertificateFromAuthServer.tbsCertificate?.version}');
        //print('SERIAL NUMBER: ${serverCertificateFromAuthServer.tbsCertificate?.serialNumber}');
        //print('VALID FROM: ${serverCertificateFromAuthServer.tbsCertificate?.validity.notBefore}');
        print('VALID UNTIL: ${serverCertificateFromAuthServer.tbsCertificate?.validity.notAfter}');
        //print('SIGNATURE ALGORITHM: ${serverCertificateFromAuthServer.tbsCertificate?.signatureAlgorithm}');
        print('PUBLIC KEY ALGORITHM: ${serverCertificateFromAuthServer.tbsCertificate?.subjectPublicKeyInfo.algorithmReadableName}');
        //print('PUBLIC KEY SHA 256 VALUE: ${serverCertificateFromAuthServer.tbsCertificate?.subjectPublicKeyInfo.sha256Thumbprint}');
        File('C:\\Users\\HP\\Desktop\\b4testdata\\b4AuthServerCertificate.pem').writeAsStringSync(serverCertificatePem);

        return {'signedCertificate':serverSignedCertificatePem, 'serverCertificate':serverCertificatePem};
    }



/// extractPublicKeyFromCertificate
    ///
    /// This function will take the input as the signed certificate and extract public key from it
    /// this function will be used when two users want to mutually authenticate each other, they will send their
    /// signed certificates to each other which can be validated by the server certificate held with both of them
    /// this public key will then be used in the mutual authentication process.
     Future<String> extractPublicKeyFromCertificate(String certificatePemFile) async {
       x509.X509CertificateData serverSignedCertContent = x509.X509Utils.x509CertificateFromPem(certificatePemFile);
       //List<String?>? allAttributes = serverSignedCertContent.tbsCertificate?.subject.entries.map((entry) => entry.value).toList();
      //String? userId = allAttributes?.elementAt(6);
       //print('User email : $userId');
       final publicKeyBytesString = serverSignedCertContent.tbsCertificate?.subjectPublicKeyInfo.bytes;
       Uint8List bytes = x509.HexUtils.decode(publicKeyBytesString!);
       ECPublicKey publicKeyExtracted = x509.CryptoUtils.ecPublicKeyFromDerBytes(bytes);
       final extractedPublicKeyPem = x509.CryptoUtils.encodeEcPublicKeyToPem(publicKeyExtracted);
       //print('extracted pub key of the user is : $extractedPublicKeyPem');
       return extractedPublicKeyPem;
     }


/// generateRandomNumber
    ///
    /// This function will create a random number which will be used in mutual authentication between two users.
    /// This random number will be used to generate a symmetric key which will be used to encrypt the data.
    Future<String> generateRandomNumber() async {
      final keyBytes = Uint8List(32);
      final random = Random.secure();
      for (int i = 0; i < keyBytes.length; i++) {
        keyBytes[i] = random.nextInt(256);
      }
      final randomNumber = base64Encode(keyBytes);
      // print('random number string is : $randomNumber');
      return randomNumber;
    }


/// generateRandomKey
    ///
    /// This function will take two random numbers as input, one is self generated and the other one is received
    /// from the remote user.
    Future<String> generateRandomKey(String randomNum1, String randomNum2) async {
    final randomNumBytes1 = base64Decode(randomNum1);
    final randomNumBytes2 = base64Decode(randomNum2);
    final combinedBytes = Uint8List.fromList(randomNumBytes2 + randomNumBytes1);
    final randomKeyConcatenation = base64Encode(combinedBytes);
    //print('generated random key by concatenation: $randomKeyConcatenation');
    final randomKeyCombinedBytesHash = crypto_utils.CryptoUtils.getHash(combinedBytes);
    //print('generated random key by Hashing: randomKeyCombinedBytesHash');

    final xorBytes = Uint8List(randomNumBytes1.length);
    for (var i = 0; i < randomNumBytes1.length; i++) {
      xorBytes[i] = randomNumBytes1[i] ^ randomNumBytes2[i];
    }
    final randomKey = crypto_utils.CryptoUtils.getHash(xorBytes);
    //print('generated random key by XOR and Hashing: $randomKey');
   // final randomKeyBytes = base64.decode(xorBytesHash);
    //final randomKeyString = base64.encode(randomKeyBytes);
    //print('random key string base 64: $randomKeyString');

    //final xorBytes2 = Uint8List(randomNumBytes2.length);
   // for (var i = 0; i < randomNumBytes2.length; i++) {
   //   xorBytes2[i] = randomNumBytes2[i] ^ randomNumBytes1[i];
   // }
    //final xorBytesHash2 = crypto_utils.CryptoUtils.getHash(xorBytes2);
   // print('generated random key by XOR and Hashing other way: $xorBytesHash2');
    return randomKey;
    }


/// encryptDataWithRandomKey
    ///
    /// This function will encrypt the data with the help of the symmetric random key.
    Future<String> encryptDataWithRandomKey( data,  randomKey) async {
      final key = Key.fromBase16(randomKey);
      final initVector = IV.fromBase16(randomKey); // Initialization vector
      final encrypter = Encrypter(AES(key, mode: AESMode.gcm )); // AES encryption with the key
      final encrypted = encrypter.encrypt(data, iv: initVector);
      final encryptedDataString = encrypted.base64;
      //print('encrypted data is : $encryptedDataString');
      return encryptedDataString;
    }



/// decryptDataWithRandomKey
    ///
    /// This function will decrypt the ciphertext with the help of the symmetric random key.
    Future<String> decryptDataWithRandomKey( encryptedData, randomKey ) async{
      final key = Key.fromBase16(randomKey);
      final initVector = IV.fromBase16(randomKey); // Initialization vector
      final encrypter = Encrypter(AES(key,  mode: AESMode.gcm )); // AES encryption with the key
      final encrypted = Encrypted.fromBase64(encryptedData);
      final decryptedData = encrypter.decrypt(encrypted, iv: initVector);
      //print('decrypted data is : $decryptedData');
      return decryptedData;
    }

    /// encryptWithEcc
    ///
    /// This function will encrypt the symmetric random key with the help of the public key of the remote user
    /// and own private key.
    Future<String> encryptWithEcc( data, receiverPublicKeyPem, senderPrivateKeyPem) async {
      final receiverPublicKey = crypto_utils.CryptoUtils.ecPublicKeyFromPem(receiverPublicKeyPem) ;
      final senderPrivateKey = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(senderPrivateKeyPem);
      final agreement = ECDHBasicAgreement();
      agreement.init(senderPrivateKey);
      final sharedSecret = agreement.calculateAgreement(receiverPublicKey);
      //print('ss is : $ss');
      final sharedSecretString = sharedSecret.toString();
      final sharedSecretBytes = utf8.encode(sharedSecretString);
      final commonSecret = crypto_utils.CryptoUtils.getHash(sharedSecretBytes);
      //print('commonSecret : $commonSecret');
      final key = Key.fromBase16(commonSecret);
      final initVector = IV.fromBase16(commonSecret); // Initialization vector
      final encrypter = Encrypter(AES(key, mode: AESMode.gcm )); // AES encryption with the key
      final encrypted = encrypter.encrypt(data, iv: initVector);
      final encryptedDataWithEccString = encrypted.base64;
      //print('encrypted data is : $encryptedDataWithEccString');
      return encryptedDataWithEccString;
    }


    /// decryptWithEcc
    ///
    /// This function will decrypt the symmetric random key with the help of the own private key and
    /// public key of the remote user.
    Future<String> decryptWithEcc( encryptedData, receiverPrivateKeyPem, senderPublicKeyPem) async {
      final receiverPrivateKey = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(receiverPrivateKeyPem);
      final senderPublicKey = crypto_utils.CryptoUtils.ecPublicKeyFromPem(senderPublicKeyPem) ;
      final agreement = ECDHBasicAgreement();
      agreement.init(receiverPrivateKey);
      final sharedSecretRemote = agreement.calculateAgreement(senderPublicKey);
      final sharedSecretRemoteString = sharedSecretRemote.toString();
      final sharedSecret2Bytes = utf8.encode(sharedSecretRemoteString);
      final commonSecretRemote = crypto_utils.CryptoUtils.getHash(sharedSecret2Bytes);
     // print('commonSecretRemote: $commonSecretRemote');
      final key = Key.fromBase16(commonSecretRemote);
      final initVector = IV.fromBase16(commonSecretRemote); // Initialization vector
      final encrypter = Encrypter(AES(key,  mode: AESMode.gcm )); // AES encryption with the key
      final encrypted = Encrypted.fromBase64(encryptedData);
      final decryptedDataWithEcc = encrypter.decrypt(encrypted, iv: initVector);
      //print('decrypted data is : $decryptedDataWithEcc');
      return decryptedDataWithEcc;
    }










    /// isValidEmail
    ///
    /// This bool value has been used so that the userID attribute in the user certificate creation is a proper
    /// email id and not some random text.
    bool isValidEmail(String userID) {
        final emailRegExp = RegExp(r'^[\w-.]+@([\w-]+\.)+[\w-]{2,4}$');
        return emailRegExp.hasMatch(userID);
    }


/// genUsersForMutAuth
    ///
    /// This function was used to generate two users for testing purpose only of ECC mutual authentication.
  genUsersForMutAuth(){
    final commonName = 'user1';
    final organization = 'user1';
    final country = 'user1';
    final attributes1 = {
      'C': country,
      'O': organization,
      'CN': commonName,
      // for user email ID
    };
    final eccKeyPair = crypto_utils.CryptoUtils.generateEcKeyPair();
    final privateKeyOne = eccKeyPair.privateKey as x509.ECPrivateKey;
    final publicKeyOne = eccKeyPair.publicKey as x509.ECPublicKey;
    final user1PrivateKeyPem = crypto_utils.CryptoUtils.encodeEcPrivateKeyToPem(privateKeyOne);
    File('C:\\Users\\HP\\Desktop\\b4testdata\\user1PrivateKey.pem').writeAsStringSync(user1PrivateKeyPem);
    final user1PublicKeyPem = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(publicKeyOne);
    File('C:\\Users\\HP\\Desktop\\b4testdata\\user1PublicKey.pem').writeAsStringSync(user1PublicKeyPem);
    final csr = x509.X509Utils.generateEccCsrPem(attributes1, privateKeyOne, publicKeyOne);
    final user1Certificate = x509.X509Utils.generateSelfSignedCertificate(privateKeyOne, csr, 365);
    File('C:\\Users\\HP\\Desktop\\b4testdata\\user1Certificate.pem').writeAsStringSync(user1Certificate);

    final commonName2 = 'user2';
    final organization2 = 'user2';
    final country2 = 'user2';
    final attributes2 = {
      'C': country2,
      'O': organization2,
      'CN': commonName2,
      // for user email ID
    };
    final eccKeyPairTwo = crypto_utils.CryptoUtils.generateEcKeyPair();
    final privateKeyTwo = eccKeyPairTwo.privateKey as x509.ECPrivateKey;
    final publicKeyTwo = eccKeyPairTwo.publicKey as x509.ECPublicKey;
    final user2PrivateKeyPem = crypto_utils.CryptoUtils.encodeEcPrivateKeyToPem(privateKeyTwo);
    File('C:\\Users\\HP\\Desktop\\b4testdata\\user2PrivateKey.pem').writeAsStringSync(user2PrivateKeyPem);
    final user2PublicKeyPem = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(publicKeyTwo);
    File('C:\\Users\\HP\\Desktop\\b4testdata\\user2PublicKey.pem').writeAsStringSync(user2PublicKeyPem);
    final csr2 = x509.X509Utils.generateEccCsrPem(attributes2, privateKeyTwo, publicKeyTwo);
    final user2Certificate = x509.X509Utils.generateSelfSignedCertificate(privateKeyTwo, csr2, 365);
    File('C:\\Users\\HP\\Desktop\\b4testdata\\user2Certificate.pem').writeAsStringSync(user2Certificate);
  }



}



/* Future<PaymentResponse?> paymentInitiation(
        double amount, // Amount in paise (e.g., 1000 for Rs. 10.00)
        String order_Id, // Unique order ID generated by your server
        String name, // Merchant name
        String description, // Description of the product/service
        String apiKey , // Your Razorpay API key (replace with your actual key)
            {
          String contact = '', // Optional: Customer's contact number
          String email = '', // Optional: Customer's email address
        }
        ) async {
      // Initialize Razorpay instance
      final razorpay = Razorpay();

      Future<PaymentResponse> handlePaymentSuccess(PaymentSuccessResponse response) async {
        return PaymentResponse(success: true, paymentId: response.paymentId);
      }

      Future<PaymentResponse?> handlePaymentError(PaymentFailureResponse response) async {
        return PaymentResponse(success: false, errorMessage: response.message);
      }

      Future<PaymentResponse?> handleExternalWallet(ExternalWalletResponse response) async {
        return PaymentResponse(success: false, errorMessage: 'External wallet selected');
      }



      // Configure payment options
      final options = {
        'key': apiKey,
        'amount': amount, // Amount in paise
        'currency': 'INR',
        'name': name,
        'description': description,
        'order_id': order_Id,
        'timeout': 120, // Payment gateway timeout in seconds (optional)
        'prefill': {
          'contact': contact, // Use provided contact number
          'email': email, // Use provided email address
        },
        'external': {'wallets': ['paytm']},
      };

      try {
        razorpay.open(options);

        // Use a Future.delayed to simulate waiting for payment completion (adjust duration as needed)
        //await Future.delayed(Duration(seconds: 5)); // Wait for 5 seconds
        razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, handlePaymentSuccess);
        razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, handlePaymentError);
        razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, handleExternalWallet);
        // You can add additional logic here to check for payment success or failure
        // For example, check a flag set in the handlePaymentSuccess/handlePaymentError functions
        // and return the appropriate PaymentResponse based on the result

      } catch (error) {
        debugPrint('Error: $error');
        return PaymentResponse(success: false, errorMessage: error.toString());
      } finally {
        // Clear Razorpay instance after payment process
        razorpay.clear();
      }

      // Return null if payment status is not determined within the timeout
      return null;
    }*/




/* Future<PaymentResponse?> paymentInitiation(
        double amount, // Amount in paise (e.g., 1000 for Rs. 10.00)
        String order_Id, // Unique order ID generated by your server
        String name, // Merchant name
        String description, // Description of the product/service
        String apiKey , // Your Razorpay API key (replace with your actual key)
            {
          String contact = '', // Optional: Customer's contact number
          String email = '', // Optional: Customer's email address
        }
        ) async {
      // Initialize Razorpay instance
      final razorpay = Razorpay();
      final paymentCompleter = Completer<PaymentResponse?>();


      void handlePaymentSuccess(PaymentSuccessResponse response) async {
        paymentCompleter.complete( PaymentResponse(success: true, paymentId: response.paymentId));

      }

      void handlePaymentError(PaymentFailureResponse response) async {
        paymentCompleter.complete(
            PaymentResponse(success: false, errorMessage: response.message));
      }

      void handleExternalWallet(ExternalWalletResponse response) async {
        paymentCompleter.complete(PaymentResponse(
            success: false, errorMessage: 'External wallet selected'));
      }

      // Configure payment options
      final options = {
        'key': apiKey,
        'amount': amount ,
        'currency': 'INR',
        'name': name,
        'description': description,
        'order_id': order_Id,
        'timeout': 120, // Payment gateway timeout in seconds (optional)
        'prefill': {
          'contact': '1234567890',
          'email': 'kinginder@rediffmail.com',
        },
        'external': { 'wallets': ['paytm'],},
      };

      try {
        // Open Razorpay checkout
          razorpay.open(options);
          razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, handlePaymentSuccess);
          razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, handlePaymentError);
          razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, handleExternalWallet);

      } catch (error) {
        debugPrint('Error: $error');
        paymentCompleter.complete(PaymentResponse(success: false, errorMessage: error.toString()));
      }

      print('payment response : $paymentCompleter');
      razorpay.clear();
      return paymentCompleter.future;
    }*/



/* // Handle payment response from Razorpay (requires server-side integration)
      final stream = _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS,  );
     // stream.listen((event) async {
        if (event[Razorpay.EVENT_PAYMENT_ERROR] == true) {
          final PaymentFailureResponse failureResponse = PaymentFailureResponse.fromMap(event);
          debugPrint('Payment failed: ${failureResponse.message}');
          return PaymentResponse.error(failureResponse.message);
        } else if (event[Razorpay.EVENT_PAYMENT_SUCCESS] == true) {
          final PaymentSuccessResponse successResponse = PaymentSuccessResponse.fromMap(event);
          debugPrint('Payment successful: ${successResponse.paymentId}');
          return PaymentResponse.success(successResponse.paymentId);
        }
      });
      _razorpay.clear();*/




/*class PaymentResponse {
  final bool success;
  final String? paymentId;
  final String? errorMessage;
  PaymentResponse({required this.success, this.paymentId, this.errorMessage});

  //PaymentResponse.success(this.paymentId) : success = true, errorMessage = null;
  //PaymentResponse.error(this.errorMessage) : success = false, paymentId = null;
}*/




/////////////write the certificate to a path in the local machine for server signature verification
//Directory documentsDirectory = await getApplicationDocumentsDirectory();
//String certificatePath = '${documentsDirectory.path}/dummyServerCertificate.pem';
//File certificateFile = File('C:\\Users\\HP\\Desktop\\b4testdata');
//certificateFile.writeAsStringSync(x509cert);
//print('certificate called from package written to local storage');
///////////////////////////////////////////////////////////////

/*
        //////////read contents to get the email ///////
        x509.X509CertificateData selfSignedCertificateContent = x509.X509Utils.x509CertificateFromPem(x509cert);
        if (kDebugMode) {
          print('SUBJECT: ${selfSignedCertificateContent.tbsCertificate?.subject}');
        }
        if (kDebugMode) {
          print('ISSUER: ${selfSignedCertificateContent.tbsCertificate?.issuer}');
        }
        if (kDebugMode) {
          print('VERSION: ${selfSignedCertificateContent.tbsCertificate?.version}');
        }
        if (kDebugMode) {
          print('SERIAL NUMBER: ${selfSignedCertificateContent.tbsCertificate?.serialNumber}');
        }
        if (kDebugMode) {
          print('VALID FROM: ${selfSignedCertificateContent.tbsCertificate?.validity.notBefore}');
        }
        if (kDebugMode) {
          print('VALID UNTIL: ${selfSignedCertificateContent.tbsCertificate?.validity.notAfter}');
        }
        if (kDebugMode) {
          print('SIGNATURE ALGORITHM: ${selfSignedCertificateContent.tbsCertificate?.signatureAlgorithm}');
        }
        if (kDebugMode) {
          print('PUBLIC KEY ALGORITHM: ${selfSignedCertificateContent.tbsCertificate?.subjectPublicKeyInfo.algorithmReadableName}');
        }
        if (kDebugMode) {
          print('PUBLIC KEY SHA 256 VALUE: ${selfSignedCertificateContent.tbsCertificate?.subjectPublicKeyInfo.sha256Thumbprint}');
        }


        if (kDebugMode) {
          print('FIRST ATTRIB CLIENT CERTIFICATE COUNTRY: ${selfSignedCertificateContent.tbsCertificate?.subject.entries.first.value}');
        }

        String? lastAttrib = selfSignedCertificateContent.tbsCertificate?.subject.entries.last.value;
        if (kDebugMode) {
          print('LAST ATTRIB: $lastAttrib');
        }
        List<String?>? allAttributes = selfSignedCertificateContent.tbsCertificate?.subject.entries.map((entry) => entry.value).toList();
        if (kDebugMode) {
          print('ALL ATTRIBUTES: $allAttributes');
        }
        String? clientemail = allAttributes?.elementAt(6);
        if (kDebugMode) {
          print('Client email : $clientemail');
        }
        */
/////////////////////////////////////////////////




/// LocalStorageValueType
///
/// has been used so as to save the generated certificate, public and private key to local storage for testing purpose.
/*enum LocalStorageValueType {
    serverCertificate,  // for testing purpose this certificate will be used as server certificate.
    serverPrivateKey,  // for testing purpose this key will be used again to sign a client csr.
    serverPublicKey,
    nodeid,
}*/

///////////The parameters below are for testing purpose only////////////////////
String dn1country = " ";
String dn2organization = " ";
String dn3commonName = " ";
String dn4surname = " ";
String dn5stateOrProvinceName = " ";
String dn6givenName = " ";
String dn7userID = " ";

/*Future<String?> getNodeId() async {
            LocalNodeID localnd = LocalNodeID();
            String? nodeId = localnd.nodeid.hashID;
            File('C:\\Users\\HP\\Desktop\\b4testdata\\nodeid').writeAsStringSync(nodeId);
            print("the value of node id generated is: $nodeId");
            return nodeId;
        }*/



//final decryptedDataWithPrivateKey = crypto_utils.CryptoUtils.rsaDecrypt(cipherText, privateKey);

//final parameter = ECDHKDFParameters(receiverPrivateKey, senderPublicKey);
//final derivator = ECDHKeyDerivator();
//derivator.init(parameter);
//KeyPair keypair = crypto.AsymmetricKeyPair(senderPublicKey, senderPrivateKey)  ;


//final algorithm = Ecdh.p256(length: 256);
//final sharedSecret = algorithm.sharedSecretKey(keyPair: kp1, remotePublicKey: receiverPublicKey);
//final ssString = sharedSecret.toString();
//print('ssString : $ssString');
// final key = Key.fromUtf8(ssString);
// final initVector = IV.fromBase16(ssString); // Initialization vector
// final encrypter = Encrypter(AES(key, mode: AESMode.gcm )); // AES encryption with the key
// final encrypted = encrypter.encrypt(data, iv: initVector);
//final encryptedDataWithPublicKey = encrypted.base64;
//print('encrypted data is : $encryptedDataWithPublicKey');
//final
//final encryptedDataWithPublicKey = crypto_utils.CryptoUtils.rsaEncrypt(data, publicKey);
//final senderPublicKey = crypto_utils.CryptoUtils.ecPublicKeyFromPem(senderPublicKeyPem);
//final senderPublicKey = SimplePublicKey(senderPublicKeyBytes, type:KeyPairType.p256);
//final kp1 = crypto.AsymmetricKeyPair(senderPublicKey, senderPrivateKey) as KeyPair;
//final parameter = ECDHKDFParameters(senderPrivateKey, receiverPublicKey);
//final derivator = ECDHKeyDerivator();
//derivator.init(parameter);


/*Future<String> encryptSymmetricKeyWithEcc(String receiverAuthenticCertificate,
        String senderPrivateKeyPem, String symmetricKeyString) async {
      Uint8List ecPrivateKeyBytes = x509.CryptoUtils.getBytesFromPEMString(senderPrivateKeyPem);
      SVPrivateKey senderPrivateKey = SVPrivateKey.fromBuffer(ecPrivateKeyBytes);
      x509.X509CertificateData receiverCertContent = x509.X509Utils.x509CertificateFromPem(receiverAuthenticCertificate);
      final publicKeyBytesString = receiverCertContent.tbsCertificate?.subjectPublicKeyInfo.bytes;
      Uint8List receiverBytes = x509.HexUtils.decode(publicKeyBytesString!);
      ASN1Object asn1Object = ASN1Parser(receiverBytes).nextObject()!;
      final newBytes = asn1Object.valueBytes?.toList();
      SVPublicKey pubKey = SVPublicKey.fromBuffer(newBytes!);
      final messageBuffer = base64Decode(symmetricKeyString);
      final ecies = Ecies();
      final encryptedData = ecies.AESEncrypt(messageBuffer, senderPrivateKey, pubKey);
      print('encrypt key and hmac : $encryptedData');
      final encryptedKeyString  = base64Encode(encryptedData);
      print('encrypt key and hmac string repre : $encryptedKeyString');
      return encryptedKeyString;
    }*/

// ECPoint? pubKeyPoints = ECCurve_prime256v1().curve.decodePoint(receiverBytes);
//BigInt? x = pubKeyPoints?.x!.toBigInteger();
// BigInt? y = pubKeyPoints?.y!.toBigInteger();
//ECPrivateKey privateKey = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(senderPrivateKeyPem);

//final yValue = y?.isOdd;
//final share = senderPrivateKey.parameters!.G! * receiverPublicKeyExtracted.Q;
//final para  = ECDHKDFParameters(senderPrivateKey, receiverPublicKeyExtracted);

// final kd = ECDHKeyDerivator();
//  kd.init(para);

//  final midprivatekey = kd.parameters.privateKey;
// final midpublickey = kd.parameters.publicKey;
//final keyAgreement = ECDHBasicAgreement();
// keyAgreement.init(senderPrivateKey);
//final sharedSecret = keyAgreement.calculateAgreement(receiverPublicKeyExtracted);
//  print('shared secret big int : $sharedSecret');
//  final bigintlength = sharedSecret.bitLength;
// print('bigintlength : $bigintlength');
// final sharedSecretString =sharedSecret.toString();
// print('shared secret string : $sharedSecretString');
// final sslength = sharedSecretString.length;
//  print('sslength : $sslength ');
// ECPublicKey receiverPublicKeyExtracted = x509.CryptoUtils.ecPublicKeyFromDerBytes(receiverBytes);
//SVPublicKey keys = SVPublicKey.fromHex(publicKeyBytesString);
//ECCurve curve = ECCurve_prime256v1();

//String xValue = x.toString();
/*Future<String> decryptSymmetricKeyWithEcc(String senderAuthenticCertificate,
        String receiverPrivateKeyPem) async {
      ECPrivateKey receiverPrivateKey = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(receiverPrivateKeyPem);

      x509.X509CertificateData senderCertContent = x509.X509Utils.x509CertificateFromPem(senderAuthenticCertificate);
      final publicKeyBytesString = senderCertContent.tbsCertificate?.subjectPublicKeyInfo.bytes;
      Uint8List senderBytes = x509.HexUtils.decode(publicKeyBytesString!);
      ECPublicKey senderPublicKeyExtracted = x509.CryptoUtils.ecPublicKeyFromDerBytes(senderBytes);
      final keyAgreement = ECDHBasicAgreement();
      keyAgreement.init(receiverPrivateKey);

      final sharedSecretAgain = keyAgreement.calculateAgreement(senderPublicKeyExtracted);
      print('shared secret again big int : $sharedSecretAgain');
      final bigintlengthAgain = sharedSecretAgain.bitLength;
      print('bigintlengthagain : $bigintlengthAgain');
      final sharedSecretAgainString =sharedSecretAgain.toString();
      print('shared secret string again : $sharedSecretAgainString');
      final sslengthAgain = sharedSecretAgainString.length;
      print('sslengthagain : $sslengthAgain ');
      return sharedSecretAgainString ;
    }*/

// final pararec  = ECDHKDFParameters(receiverPrivateKey, senderPublicKeyExtracted);

//final kdrec = ECDHKeyDerivator();
//kdrec.init(pararec);
//final midprivatekeyrec = kdrec.parameters.privateKey;
//final midpublickeyrec = kdrec.parameters.publicKey;

//final BigInt privateKeyValue = midprivatekeyrec.d!;
// final ECPoint publicKeyPoint = midpublickeyrec.Q!;

// final BigInt sharedSecretAgain = privateKeyValue * (publicKeyPoint.x?.toBigInteger() ?? BigInt.zero);






// final BigInt privateKeyValue = midprivatekey.d!;
// final ECPoint publicKeyPoint = midpublickey.Q!;

// final BigInt sharedSecret = privateKeyValue * (publicKeyPoint.x?.toBigInteger() ?? BigInt.zero);

//final keys = Key.fromBase16(sharedSecretString);
//final init = IV.fromBase16(sharedSecretString);
//final process = Encrypter(AES(keys, mode: AESMode.gcm));
//final encrypted  = process.encrypt(symmetricKeyString,iv: init);
//final encryptedSymmetricKey = encrypted.base64;
// print('secret string : $sharedSecretString ');
//List<int> bytes = utf8.encode(sharedSecretString);
//final sharedSecretStringBase64 = base64Encode(bytes);
//final base64length = sharedSecretStringBase64.length


//final padded = '${sharedSecretString}0';

// Uint8List utf8Bytes = utf8.encode(sharedSecretString);
// SHA256Digest digest = SHA256Digest();
// List<int> hashedBytes = digest.process(utf8Bytes);
//String hashString = base64Encode(hashedBytes);
// print('hash : $hashString');


// print('encrypted symmetric key : $encryptedSymmetricKey');

//final symmetricKeyBytes = base64Decode(symmetricKeyString);

//BigInt? d_sender = senderPrivateKey.d;
//var ecdh = ECDHKDFParameters(senderPrivateKey, publicKeyExtracted);
//ECDHKeyDerivator();
//ECPoint S = (d_sender! * publicKeyExtracted.Q) ;


//Uint8List ecPrivateKeyBytes = x509.CryptoUtils.getBytesFromPEMString(senderPrivateKeyPem);




/*List<int> AESEncrypt(List<int> messageBuffer, SVPrivateKey senderPrivateKey, SVPublicKey recipientPublicKey){
      final ecies = Ecies();
      SVPublicKey asdfg = crypto_utils.CryptoUtils.(pem) as SVPublicKey;

      //Encryption requires derivation of a cipher using the other party's Public Key
      // Bob is sender, Alice is recipient of encrypted message
      // Qb = k o Qa, where
      //     Qb = Bob's Public Key;
      //     k = Bob's private key;
      //     Qa = Alice's public key;

      final ECPoint S = (recipientPublicKey.point * senderPrivateKey.privateKey)!; //point multiplication
      final pubkeyS = SVPublicKey.fromXY(S.x!.toBigInteger()!, S.y!.toBigInteger()!);
      final pubkeyBuffer = HEX.decode(pubkeyS.getEncoded(true));
      final pubkeyHash = SHA512Digest().process(pubkeyBuffer as Uint8List);

      //initialization vector parameters
      final iv = pubkeyHash.sublist(0, 16);
      final kE = pubkeyHash.sublist(16, 32);
      final kM = pubkeyHash.sublist(32, 64);

      CipherParameters params = PaddedBlockCipherParameters(ParametersWithIV(KeyParameter(kE), iv), null);
      BlockCipher encryptionCipher = PaddedBlockCipher('AES/CBC/PKCS7');
      encryptionCipher.init(true, params);

      final cipherText = encryptionCipher.process(messageBuffer as Uint8List);
      final magic = utf8.encode('BIE1');

      final encodedBuffer = Uint8List.fromList(magic + HEX.decode(senderPrivateKey.publicKey.toHex()) + cipherText);

      //calc checksum
      final hmac = _calculateHmac(kM, encodedBuffer);

      return encodedBuffer + hmac;
    }*/

/*Future<String> encryptSymmetricKeyWithPublicKey(String symmetricKeyString, String receiverAuthenticCertificate,
        String senderPrivateKeyPem) async {
      final ecies = Ecies();
      final symmetricKeyBytes = base64Decode(symmetricKeyString);
      Uint8List ecPrivateKeyBytes = x509.CryptoUtils.getBytesFromPEMString(senderPrivateKeyPem);
      SVPrivateKey senderPrivateKey = SVPrivateKey.fromBuffer(ecPrivateKeyBytes);
      print('SV pvt key generated');
      x509.X509CertificateData receiverCertContent = x509.X509Utils.x509CertificateFromPem(receiverAuthenticCertificate);
      final publicKeyBytesString = receiverCertContent.tbsCertificate?.subjectPublicKeyInfo.bytes;
      Uint8List receiverBytes = x509.HexUtils.decode(publicKeyBytesString!);
      ASN1Parser parser = ASN1Parser(receiverBytes);
      ASN1Sequence sequence = parser.nextObject() as ASN1Sequence;
      List<Uint8List> derElements = [];
      if (sequence.elements != null) {
        for (ASN1Object element in sequence.elements!) {
          derElements.add(element.encode());
        }
      }
      Uint8List derBytes = Uint8List.fromList(derElements.expand((e) => e).toList());

      //print('Receiver Bytes: ${receiverBytes.map((byte) => byte.toRadixString(16)).toList()}');
      /*try {
        ECPoint? publicKeyPoint = ECCurve_secp256k1().curve.decodePoint(receiverBytes);
        if (publicKeyPoint != null) {
          BigInt? x = publicKeyPoint.x!.toBigInteger();
          BigInt? y = publicKeyPoint.y!.toBigInteger();
          print('x component: $x');
          print('y component: $y');
        } else {
          print('Failed to decode ECPoint.');
        }
      } catch (e) {
        print('Error decoding ECPoint: $e');
      }*/
      //ECPublicKey publicKeyExtracted = x509.CryptoUtils.ecPublicKeyFromDerBytes(receiverBytes);
      //ECPoint? q = (publicKeyExtracted as ECPublicKeyParameters).Q;
      //BigInt x = q?.getAffineXCoord() as BigInt;
      //final bytesFull = receiverBytes.sublist(53);

      SVPublicKey receiverPublicKey = SVPublicKey.fromDER(derBytes);
      print('SV public key generated');
      final encryptedData = ecies.AESEncrypt(symmetricKeyBytes, senderPrivateKey, receiverPublicKey);
      print('encrypt key and hmac : $encryptedData');
      final encryptedKeyString  = base64Encode(encryptedData);
      print('encrypt key and hmac string repre : $encryptedKeyString');
      return encryptedKeyString;
    }*/
//Uint8List ecPublicKeyBytes = x509.CryptoUtils.getBytesFromPEMString(receiverPublicKeyPem);


//String pubKeyHex = x509.HexUtils.encode(ecPublicKeyBytes);
//ECPublicKey ecPublicKey = crypto_utils.CryptoUtils.ecPublicKeyFromPem(receiverPublicKeyPem);
// ASN1Sequence sequence = ASN1Sequence();
// ASN1ObjectIdentifier curveIdentifier = ASN1ObjectIdentifier.fromName('secp256k1');
//ASN1BitString curveBitString = ASN1BitString( );
// sequence.add(curveBitString);
//ASN1BitString publicKeyBitString = ASN1BitString( ecPublicKeyBytes);
//sequence.add(publicKeyBitString);
//final examplepub = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(ecPublicKey);
//print('example public key gene again : $examplepub');

//print('public key bytes generated');

//SVPublicKey receiverPublicKey = SVPublicKey.fromBuffer(ecPublicKeyBytes);
//String ecPublicKeyHex = x509.HexUtils.encode(ecPublicKeyBytes);
//ECPrivateKey ecPrivateKey = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(senderPrivateKeyPem);
//String ecPrivateKeyHexString = x509.HexUtils.encode(ecPrivateKeyBytes);

//Uint8List privateKeyBytes = ecPrivateKey.d as Uint8List;
//BigInt privateKeyBigInt = BigInt.fromBytes(Endian.big, privateKeyBytes);
//ecies.init(true, ParametersWithRandom(PublicKeyParameter(receiverPublicKey), null));
//final encryptedKey = ecies.processBlock(symmetricKeyBytes, 0, symmetricKeyBytes.length);
//final encryptedKeyString = base64Encode(encryptedKey);
//ECPublicKey receiverPublicKey = crypto_utils.CryptoUtils.ecPublicKeyFromPem(receiverPublicKeyPem);

/*Future<List<int>> encryptSymmetricKey(String symmetricKeyString, String senderPrivateKeyPem,
        String recipientPublicKeyPem) async{
      final messageBuffer = base64Decode(symmetricKeyString);
      final recipientPublicKey = crypto_utils.CryptoUtils.ecPublicKeyFromPem(recipientPublicKeyPem);
      final senderPrivateKey = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(senderPrivateKeyPem);
      //Encryption requires derivation of a cipher using the other party's Public Key
      // Bob is sender, Alice is recipient of encrypted message
      // Qb = k o Qa, where
      //     Qb = Bob's Public Key;
      //     k = Bob's private key;
      //     Qa = Alice's public key;

      final ECPoint S = (recipientPublicKey.Q! * senderPrivateKey.d)!;
      //final ECPoint? S = (recipientPublicKey.Q! * senderPrivateKey);
      //final pubkeyS = PublicKey.fromXY(S.x!.toBigInteger()!, S.y!.toBigInteger()!);
      final pubKeyS = SVPublicKey(S);
      final pubkeyBuffer = HEX.decode(pubkeyS.getEncoded(true));
      final pubkeyHash = SHA512Digest().process(pubkeyBuffer as Uint8List);

      //initialization vector parameters
      final iv = pubkeyHash.sublist(0, 16);
      final kE = pubkeyHash.sublist(16, 32);
      final kM = pubkeyHash.sublist(32, 64);

      CipherParameters params = PaddedBlockCipherParameters(ParametersWithIV(KeyParameter(kE), iv), null);
      BlockCipher encryptionCipher = PaddedBlockCipher('AES/CBC/PKCS7');
      encryptionCipher.init(true, params);

      final cipherText = encryptionCipher.process(messageBuffer as Uint8List);
      final magic = utf8.encode('BIE1');

      final encodedBuffer = Uint8List.fromList(magic + HEX.decode(senderPrivateKey.publicKey.toHex()) + cipherText);

      //calc checksum
      final hmac = _calculateHmac(kM, encodedBuffer);

      return encodedBuffer + hmac;
    }*/

/// saveToLocalStorage
///
/// The aim of this function is just to save the certificate, public and private key generated locally
/// as sever certificate and keys for testing purpose only.
/*Future<void> saveToLocalStorage(String serverCertificate, String serverPrivateKey, String serverPublicKey,
                                    String file1,String file2,String file3 ) async {
        String? serverCertificate = generatedCertificate?.x509cert;  // the same certificate generated is saved as server certificate to be later used for testing
        String? serverPrivateKey = generatedCertificate?.privateKeyPem;  // the same private key is saved as server private key to be later used for testing
        //String? serverPublicKey = generatedCertificate?.publicKeyPem; // the same public key is saved as server public key to be later used for testing

        File(file1).writeAsStringSync(serverCertificate!);
        File(file2).writeAsStringSync(serverPrivateKey!);
        //File(file3).writeAsStringSync(serverPublicKey!);

    }*/




/// readFromLocalStorage
///
/// The purpose of this is to simply read the values of certificate and keys from local storage
/// so that they can be use to test different functions. This function returns certificaate, public, private key
/// whatever is required for testing.
/*Future<String> readFromLocalStorage(LocalStorageValueType file) async {
        String path;
        switch (file) {
        case LocalStorageValueType.serverCertificate:
            path = 'C:\\Users\\HP\\Desktop\\b4testdata\\serverCertificate.pem';
            break;
        case LocalStorageValueType.serverPrivateKey:
            path = 'C:\\Users\\HP\\Desktop\\b4testdata\\serverPrivateKey.pem';
            break;
        case LocalStorageValueType.serverPublicKey:
            path = 'C:\\Users\\HP\\Desktop\\b4testdata\\serverPublicKey.pem';
            break;
        case LocalStorageValueType.nodeid:
            path = 'C:\\Users\\HP\\Desktop\\b4testdata\\nodeid';
            break;
        }
        final value = File(path).readAsStringSync();
        return value;
    }*/




/// createClientCsrAndServerSignedCertificate
///
/// This function generates a client CSR which is used for testing purpose by signing it with the private key
/// of the generateSelfSignedUserCertificate function the certificate which is generated is like
/// the certificate which we get from the server after signature and we use this certificate
/// for other functions.

/*Future<String> createClientCsrAndServerSignedCertificate( String dn1country,String dn2organization,String dn3commonName,
            String dn4surname,String dn5stateOrProvinceName, String dn6givenName, String dn7userID ) async {

        final parameters = {
'C':
            dn1country,
'O':
            dn2organization,
'CN':
            dn3commonName,
'SN':
            dn4surname,
'ST':
            dn5stateOrProvinceName,
'GN':
            dn6givenName,  // for user Aadhar ID
'UID':
            dn7userID,    // for user email ID
        };

        final eccKeyPairClient = crypto_utils.CryptoUtils.generateEcKeyPair();
        final privateKeyClient = eccKeyPairClient.privateKey as x509.ECPrivateKey;
        final publicKeyClient = eccKeyPairClient.publicKey as x509.ECPublicKey;
        //final privateKeyClientPem = crypto_utils.CryptoUtils.encodeEcPrivateKeyToPem(privateKeyClient);
        //final publicKeyClientPem = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(publicKeyClient);
        final clientCsr = x509.X509Utils.generateEccCsrPem(parameters, privateKeyClient, publicKeyClient);


        //final data2Future = readFromLocalStorage(LocalStorageValueType.serverPrivateKey);
        //final serverPrivateKeyPem = await data2Future;
        String? serverPrivateKeyPem = File('C:\\Users\\HP\\Desktop\\b4testdata\\serverPrivateKey.pem').readAsStringSync();
        final serverPrivateKeyToSign = crypto_utils.CryptoUtils.ecPrivateKeyFromPem(serverPrivateKeyPem);
        final serverSignedCertificate = x509.X509Utils.generateSelfSignedCertificate(serverPrivateKeyToSign, clientCsr, 365);
        File('C:\\Users\\HP\\Desktop\\b4testdata\\serverSignedCertificate.pem').writeAsStringSync(serverSignedCertificate);
        print("the user signed certificate generated is: $serverSignedCertificate");
        return serverSignedCertificate;
    }*/








/* ASN1Parser asn1ParserPublicKeyBytes = ASN1Parser(publicKeyBytes);
       ASN1Sequence sequencePublicKey = asn1ParserPublicKeyBytes.nextObject() as ASN1Sequence;
       ASN1Object objectPublicKey = ASN1Object.fromBytes(sequencePublicKey.encodedBytes);
       final publicKeyExtractedPem = x509.X509Utils.encodeASN1ObjectToPem(objectPublicKey,'-----BEGIN PUBLIC KEY-----', '-----END PUBLIC KEY-----');
       print('server cert received : $publicKeyExtractedPem');
       List<String?>? allAttributes = serverSignedCertContent.tbsCertificate?.subject.entries.map((entry) => entry.value).toList();
       print('ALL ATTRIBUTES: $allAttributes');
       String? userEmail = allAttributes?.elementAt(6);
       print('User email : $userEmail');*/


//Uint8List publicKeyBytes = Uint8List.fromList(utf8.encode(publicKeyBytesString!));
/*;

       ECDomainParameters domainParams = ECDomainParameters('prime256v1');
       ECPoint? ecPoint = domainParams.curve.decodePoint(publicKeyBytes);
       if (ecPoint == null) {
         print('Error decoding EC point');
         return null; // Return null if decoding fails
       }

       ECPublicKey publicKey = ECPublicKey(ecPoint, domainParams);
       final publicKeyPem = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(publicKey);
       print('Public key  : $publicKeyPem');*/
/*Uint8List certificateBytes = base64.decode(
        certificatePemFile.replaceAll(
          RegExp(r'-----BEGIN CERTIFICATE-----|-----END CERTIFICATE-----'),
          '',
        ).replaceAll('\n', ''),
      );

      ASN1Sequence asn1Seq = ASN1Sequence.fromBytes(certificateBytes);
      ASN1Sequence tbsCertificate = asn1Seq.elements?[0] as ASN1Sequence;
      ASN1Sequence subjectPublicKeyInfo = tbsCertificate
          .elements?[6] as ASN1Sequence;
      //ASN1ObjectIdentifier algorithmId = subjectPublicKeyInfo.elements?[0] as ASN1ObjectIdentifier;
      ASN1Object? algorithmId = subjectPublicKeyInfo.elements?[0];

      if (algorithmId is ASN1ObjectIdentifier &&
          algorithmId.toString() == '1.2.840.10045.2.1') {
        // ECDSA public key
        ASN1BitString publicKeyBitString = subjectPublicKeyInfo
            .elements?[1] as ASN1BitString;
        Uint8List publicKeyBytes = publicKeyBitString.valueBytes!;

        ECPoint ecPoint = ECPoint.parseFrom(publicKeyBytes);
        //ECCurve_prime256v1 curve = ECCurve_prime256v1();
        //ECPoint? ecPoint = ECCurve_prime256v1().decodePoint(publicKeyBytes)!;
        ECPublicKey publicKey = ECPublicKey.decodePoint( ECCurve_prime256v1(), publicKeyBytes);

        final userPublicKeyPem = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(
            publicKey);
        print('pub key is : $userPublicKeyPem');
        return userPublicKeyPem;
      } else {
        print('Unsupported algorithm ID: $algorithmId');
        return null;
      }*/
//print('Public key bytes: ${serverSignedCertContent.publicKeyData.bytes}');

//String publicKeyString = base64.encode(publicKeyBytes);
//final publickeypem = x509.X509Utils.formatKeyString(publicKeyString, '-----BEGIN PUBLIC KEY-----', '-----END PUBLIC KEY-----');

// final publicKey = serverSignedCertContent.tbsCertificate?.subjectPublicKeyInfo.toString();

//ECPoint? ecPoint = ECCurve_secp256r1().decodePoint(publicKeyBytes);
//ECCurve curve = ECCurve_secp256r1() ;
// ECPoint? ecPoint = curve.decodePoint(publicKeyBytes);
//ECPrivateKey privateKey = ECPrivateKey('prime256v1', BigInt.zero, ecPoint!, null);

// Create an ECDomainParameters object using the curve's parameters

// Create an ECPublicKey instance using the decoded ECPoint and ECDomainParameters


/* ASN1Parser asn1Parser = ASN1Parser(certificateBytes);
      ASN1Sequence sequence = asn1Parser.nextObject() as ASN1Sequence;


      ASN1Sequence publicKeySequence = sequence.elements?[6] as ASN1Sequence;

      ASN1BitString publicKeyBitString = publicKeySequence.elements?[1] as ASN1BitString;
      Uint8List publicKeyBytes = publicKeyBitString.valueBytes!;

      ECCurve curve = ECCurve_prime256v1() as ECCurve ;
      ECPoint? ecPoint = curve.decodePoint(publicKeyBytes);

      //ECPoint publicKeyPoint = ECCurve_prime256v1().decodePoint(publicKeyBytes)!;
      ECPublicKey publicKey = ECPublicKey(ecPoint, ECCurve_prime256v1());
      final userPublicKeyPem = crypto_utils.CryptoUtils.encodeEcPublicKeyToPem(publicKey);
      return userPublicKeyPem;*/

/*ASN1Sequence sequence = ASN1Sequence.fromBytes(base64.decode(certificatePemFile));
    ASN1Sequence publicKeySequence = sequence.elements?[0] as ASN1Sequence;
    ASN1BitString publicKeyBitString = publicKeySequence.elements?[1] as ASN1BitString;
    Uint8List encodedPublicKey = publicKeyBitString.valueBytes!;
    ASN1Parser parser = ASN1Parser(encodedPublicKey);
    ASN1ObjectIdentifier keyType = parser.nextObject() as ASN1ObjectIdentifier;
    ASN1Object publicKey = parser.nextObject();

    ECPoint ecPoint = ECPoint.fromBytes(publicKey.contentBytes()!, publicKey: ECParameters(type: 'prime256v1'));
    ECKeyGeneratorParameters keyParams = ECKeyGeneratorParameters('prime256v1' as ECDomainParameters);
    ECCurve curve = ECCurve('prime256v1');
    ECPoint ecPublicKey = curve.decodePoint(ecPoint.getEncoded());
    return ECPublicKey(ecPublicKey, ECParameters(type: 'prime256v1'));*/


/*if(_nodeIdGenerated == true){
  String? nodeId = File('C:\\Users\\HP\\Desktop\\b4testdata\\nodeId').readAsStringSync();// Wait for the future to complete
  print(" the value of stored node id called to sent is: $nodeId");
}
    else{
  LocalNodeID localnd = LocalNodeID();
  String? nodeId = localnd.nodeid.hashID;
  print("the value of new node id is: $nodeId");
  File('C:\\Users\\HP\\Desktop\\b4testdata\\nodeId').writeAsStringSync(nodeId);

}*/


/*Future<String?> getNodeId() async {
      LocalNodeID localnd = LocalNodeID();
      String? nodeId = localnd.nodeid.hashID;
      File('C:\\Users\\HP\\Desktop\\b4testdata\\nodeId').writeAsStringSync(nodeId);
      print("the value of node id generated is $nodeId");
    return nodeId;
  }*/

/*Future<String?> getMacAddress() async {
    final NetworkInfo networkInfo = NetworkInfo();
    return await networkInfo.getWifiBSSID();
  }*/

//String deviceId = GetMacAddress as String;
/*Future<String> getMacAddress() async {
    try {
      var connectivityResult = await Connectivity().checkConnectivity();
      if (connectivityResult == ConnectivityResult.wifi) {
        String? wifiBSSID = await Connectivity().getWifiBSSID();
        return wifiBSSID ?? 'MAC address not available';
      } else {
        return 'Not connected to WiFi';
      }
    } catch (e) {
      print('Error getting MAC address: $e');
      return 'Error';
    }
  }*/

/*Future<String?> getDeviceId() async {
    final DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
    String? deviceId;
    try {
      if (Platform.isAndroid) {
        const androidId = AndroidId();
        deviceId = await androidId.getId(); // Android device ID
      } else if (Platform.isIOS) {
        IosDeviceInfo iosInfo = await deviceInfo.iosInfo;
        deviceId = iosInfo.identifierForVendor; // iOS device ID
        if (deviceId != null && deviceId.isNotEmpty) {
          // Remove brackets from iOS device ID
          deviceId = deviceId.substring(1, deviceId.length - 1);
        }
      } else if (kIsWeb) {
        final webBrowserInfo = await deviceInfo.webBrowserInfo;
        deviceId = '${webBrowserInfo.vendor ?? '-'} + ${webBrowserInfo.userAgent ?? '-'} + ${webBrowserInfo.hardwareConcurrency.toString()}';
        // Construct web browser device ID
      } else if (Platform.isWindows) {
        final windowsInfo = await deviceInfo.windowsInfo;
        deviceId = windowsInfo.deviceId; // Windows device ID
      } else if (Platform.isLinux) {
        final linuxInfo = await deviceInfo.linuxInfo;
        deviceId = linuxInfo.machineId; // Linux device ID
      } else if (Platform.isMacOS) {
        final macOsInfo = await deviceInfo.macOsInfo;
        deviceId = macOsInfo.systemGUID; // macOS device ID
      }
    } catch (e) {
      print('Error getting device ID: $e');
      deviceId = null; // Handle error by returning null
    }
    print('Device ID: $deviceId');
    return deviceId;
  }*/


/* final pemHeader = '-----BEGIN CERTIFICATE-----';
    final pemFooter = '-----END CERTIFICATE-----';

    print(" decoding the base64 bytes");
    //List<int> decodedbytes = base64.decode(signedCertificatebase64);
    final decodedbytes = Uint8List.fromList(serverSignedCertificateBase64.codeUnits);
    print(" decoded  bytes   :   $decodedbytes");
    //List<dynamic> decodedBytes = base64.decode(signedCertificatebase64) ;

    //String pemString = utf8.decode(decodedbytes);
    String pemString = utf8.decode(decodedbytes);

    print(" making a string : $pemString");
    final signedCertificate = '$pemHeader\n$pemString\n$pemFooter';
    print(" making a pem format");
    if (kDebugMode) {
      print("The Signed Certificate pem format received from server is : $signedCertificate");
    }*/





////////////////// read from local storage to verify signature////////
// Directory documentsDirectory = await getApplicationDocumentsDirectory();
// String certificatePath = '${documentsDirectory.path}/dummyServerCertificate.pem';
// File certificateFile = File(certificatePath);
// String dummyServerCertificate = await certificateFile.readAsString();
//print('Reading  dummy server certificate from local storage for signature check');
////////////////////////////////////////////////////////////////////////////////////////////

/*
    ///////////////////////////////
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String certificatePath = '${documentsDirectory.path}/signedCertRecd.pem';
    File certificateFile = File(certificatePath);
    certificateFile.writeAsStringSync(signedCertificate);
    print('certificate received from server after conversion written to local storage');

    //////////////////////////////////

    List<int> derBytes = x509.PEMParser(signedCertificate).readNextAsBytes();
    //print(" data check $signedcertdata");
    x509.X509CertificateData certData = x509.X509Utils.x509CertificateFromBytes(Uint8List.fromList(derBytes));

    // Extract information from the certificate
    print('Subject: ${certData.tbsCertificate?.subject}');
    print('Issuer: ${certData.tbsCertificate?.issuer}');
    x509.X509CertificateData signedCertificateContent = x509.X509Utils.x509CertificateFromPem(signedCertificate);
    if (kDebugMode) {
      print('SUBJECT: ${signedCertificateContent.tbsCertificate?.subject}');
    }
    if (kDebugMode) {
      print('ISSUER: ${signedCertificateContent.tbsCertificate?.issuer}');
    }
    if (kDebugMode) {
      print('VERSION: ${signedCertificateContent.tbsCertificate?.version}');
    }
    if (kDebugMode) {
      print('SERIAL NUMBER: ${signedCertificateContent.tbsCertificate?.serialNumber}');
    }
    if (kDebugMode) {
      print('VALID FROM: ${signedCertificateContent.tbsCertificate?.validity.notBefore}');
    }
    if (kDebugMode) {
      print('VALID UNTIL: ${signedCertificateContent.tbsCertificate?.validity.notAfter}');
    }
    if (kDebugMode) {
      print('SIGNATURE ALGORITHM: ${signedCertificateContent.tbsCertificate?.signatureAlgorithm}');
    }
    if (kDebugMode) {
      print('PUBLIC KEY ALGORITHM: ${signedCertificateContent.tbsCertificate?.subjectPublicKeyInfo.algorithmReadableName}');
    }
    if (kDebugMode) {
      print('PUBLIC KEY SHA 256 VALUE: ${signedCertificateContent.tbsCertificate?.subjectPublicKeyInfo.sha256Thumbprint}');
    }


    if (kDebugMode) {
      print('FIRST ATTRIB SIGNED CERTIFICATE : ${signedCertificateContent.tbsCertificate?.subject.entries.first.value}');
    }

    String? lastAttrib = signedCertificateContent.tbsCertificate?.subject.entries.last.value;
    if (kDebugMode) {
      print('LAST ATTRIB SIGNED CERTIFICATE: $lastAttrib');
    }
    List<String?>? allAttributes = signedCertificateContent.tbsCertificate?.subject.entries.map((entry) => entry.value).toList();
    if (kDebugMode) {
      print('ALL ATTRIBUTES: $allAttributes');
    }*/
//CertificateData? get generatedCertificate => _generatedCertificate;
//_generatedCertificate = generatedCertificate;
//String certHash;
//required this.certHash,
//final x509certBytes = Uint8List.fromList(x509cert.codeUnits);
//final certHash = crypto_utils.CryptoUtils.getHash(x509certBytes);


//////////read contents to get the email ///////
/*x509.X509CertificateData selfSignedCertificateContent = x509.X509Utils.x509CertificateFromPem(SScert);
    if (kDebugMode) {
      print('SUBJECT: ${selfSignedCertificateContent.tbsCertificate?.subject}');
    }
    if (kDebugMode) {
      print('ISSUER: ${selfSignedCertificateContent.tbsCertificate?.issuer}');
    }
    if (kDebugMode) {
      print('VERSION: ${selfSignedCertificateContent.tbsCertificate?.version}');
    }
    if (kDebugMode) {
      print('SERIAL NUMBER: ${selfSignedCertificateContent.tbsCertificate?.serialNumber}');
    }
    if (kDebugMode) {
      print('VALID FROM: ${selfSignedCertificateContent.tbsCertificate?.validity.notBefore}');
    }
    if (kDebugMode) {
      print('VALID UNTIL: ${selfSignedCertificateContent.tbsCertificate?.validity.notAfter}');
    }
    if (kDebugMode) {
      print('SIGNATURE ALGORITHM: ${selfSignedCertificateContent.tbsCertificate?.signatureAlgorithm}');
    }
    if (kDebugMode) {
      print('PUBLIC KEY ALGORITHM: ${selfSignedCertificateContent.tbsCertificate?.subjectPublicKeyInfo.algorithmReadableName}');
    }
    if (kDebugMode) {
      print('PUBLIC KEY SHA 256 VALUE: ${selfSignedCertificateContent.tbsCertificate?.subjectPublicKeyInfo.sha256Thumbprint}');
    }


    if (kDebugMode) {
      print('FIRST ATTRIB CLIENT CERTIFICATE COUNTRY: ${selfSignedCertificateContent.tbsCertificate?.subject.entries.first.value}');
    }

    String? lastAttrib = selfSignedCertificateContent.tbsCertificate?.subject.entries.last.value;
    if (kDebugMode) {
      print('LAST ATTRIB: $lastAttrib');
    }
    List<String?>? allAttributes = selfSignedCertificateContent.tbsCertificate?.subject.entries.map((entry) => entry.value).toList();
    if (kDebugMode) {
      print('ALL ATTRIBUTES: $allAttributes');
    }
    String? clientemail = allAttributes?.elementAt(5);
    if (kDebugMode) {
      print('Client email : $clientemail');
    }*/

/////////////////////////////////////////////////

/*Future<Map<String, String>> initialize() async
    {

    String? userCertificate = certificateInfo['x509cert'];
      print('User self-signed certificate is : $userCertificate');
      String? userPvtKeyPem = certificateInfo['privateKeyPem'];
      print('User private key pem is : $userPvtKeyPem');
    return

    }*/

//String x509certHash = "";

/*Future<bool> verifyHash(String decryptedServerSignedCertificate, String decryptedHash) async {
    try {
      if (decryptedServerSignedCertificate != null && decryptedHash != null) {
        final storedCertificateBytes = Uint8List.fromList(decryptedServerSignedCertificate.codeUnits);
        final calculatedHash = crypto_utils.CryptoUtils.getHash(storedCertificateBytes);
        final hashMatches = decryptedHash == calculatedHash;
        if (kDebugMode) {
          //print('Certificate hash matches: $hashMatches');
        }
        return hashMatches;
      } else {
        print('Certificate hash does not match certificate has been tampered');
        if (kDebugMode) {
          print('Error during hash check: Invalid decryptedValues.');
        }
        return false;
      }
    } catch (e) {

      if (kDebugMode) {
        print('Error during hash check: $e');
      }
      return false; // Return false in case of an exception.
    }
  }*/

/*Future<String?> getNodeId() async {
    try {
      String? nodeId = await readFromLocalStorage(LocalStorageValueType.nodeId);
      print("the value of stored nodeid is $nodeId");

      if (nodeId == null || nodeId.isEmpty) {
        LocalNodeID localnd = LocalNodeID();
        nodeId = localnd.nodeid.hashID;
        print("the value of new nodeid is $nodeId");
        // write the response to secure storage
        // StorageItem newItem = StorageItem("nodeid", nodeId);
        // _storageService.writeSecureData(newItem);
      }

      return nodeId;
    } catch (e) {
      // Handle the error when reading the file
      print("Error reading node ID from local storage: $e");

      // Generate a new node ID
      LocalNodeID localnd = LocalNodeID();
      String newNodeId = localnd.nodeid.hashID;
      print("the value of new nodeid is $newNodeId");
      // write the response to secure storage
      // StorageItem newItem = StorageItem("nodeid", newNodeId);
      // _storageService.writeSecureData(newItem);

      return newNodeId;
    }
  }*/

