name: b4commgr
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  async: ^2.8.1
  udp: ^5.0.3
  web_socket_channel: ^2.4.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_webrtc: ^0.10.4
  sdp_transform: ^0.3.2

 # local libraries
  b4connection:
    path: ../b4connection
  b4rttable:
    path: ../b4rttable
  b4auth:
    path: ../b4auth
  nodeid:
    path: ../nodeid
  b4utils:
    path: ../b4utils

